//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWithEFDBFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int OrderId { get; set; }
        public int MedId { get; set; }
        //[Range(1,Product.Quantity,"That's the max quantity that you can buy, we don't have more than this")]
        public int OrderQuantity { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
